import type { NextPage } from 'next'
import Head from 'next/head'
import config from "../config/walletConfigs";
import styles from '../styles/Home.module.css'
import { Button, useWalletModal } from '@pancakeswap/uikit'
import useAuth from '../hooks/useAuth'
import { Flex } from '@pancakeswap-libs/uikit'
import WalletCard from '../components/walletCard';
import { useState } from 'react';

const Home: NextPage = (props) => {
  const { login, logout } = useAuth()
  const [activatingConnector, setActivatingConnector] = useState();
  // const { onPresentConnectModal } = useWalletModal(login, logout, "0xbdda50183d817c3289f895a4472eb475967dc980")
  const { onPresentConnectModal} = useWalletModal(
    login,
    logout,
    () => "0xbdda50183d817c3289f895a4472eb475967dc980"
  );
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {config.map((entry, index) => (
        <>
          <button onClick={() => { login(entry.connectorId)}}>
            {entry.title}
          </button>
        </>
        // <WalletCard
        //   key={entry.title}
        //   login={login}
        //   walletConfig={entry}
        //   onDismiss={() => null}
        //   mb={index < config.length - 1 ? "8px" : "0"}
        // />
       ))}

      <button onClick={() => { logout()}}>
        Logout
      </button>
      
    </div>
  )
}

export default Home
